version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    env_file: "webapp.env"
    environment:
      TOKEN_KEY: 'shouldbeverysecure' #demo
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://user:password@host/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESSS: 'auth:3000'